#ifndef M080R_H
#define M080R_H
#include <zephyr/drivers/sensor.h>

typedef enum {
	SENSOR_CHAN_M080R_START = SENSOR_CHAN_PRIV_START,
	SENSOR_CHAN_REGISTER_FINGERPRINT = SENSOR_CHAN_M080R_START,
	SENSOR_CHAN_SAVE_FINGERPRINT,
	SENSOR_CHAN_MATCH_FINGERPRINT,
	SENSOR_CHAN_SLEEP,
} m080r_channels_t;

typedef enum {
	SENSOR_ATTR_M080R_START = SENSOR_ATTR_PRIV_START,
	SENSOR_ATTR_NORMAL_SLEEP,
	SENSOR_ATTR_DEEP_SLEEP,
} m080r_attr_t;


#endif // M080R_H
